---
title: "Desafio2"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown


```{r bibliotecas, warning=FALSE, message=FALSE}

library(lares)
library(ggplot2)
library(dplyr)
library(readxl)
library(GGally)
```




```{r}
data <-  read_excel('ChoiceBehaviour.xlsx')
```




```{r}
freqs_df(data, plot = T)
```


```{r}
#numeric <- c("AGE", "SENIORITY")
df_pearson<- data[, -c(1,2)]


correl<- cor(df_pearson, method = 'pearson')

testRes = corrplot::cor.mtest(df_pearson, conf.level = 0.95, method = 'pearson')

corrplot::corrplot(correl, p.mat = testRes$p, addCoef.col ='black',method = 'square', order = 'FPC', type = 'lower', insig = 'blank', number.cex=0.6)
```


```{r}
hist_resp <- ggplot(data %>% count(Resposta, Regiao) %>%    
         mutate(pct=n/sum(n)),
       aes(as.factor(Resposta), n)) +
  geom_bar(stat="identity") +
  #geom_text(aes(label=paste0(sprintf("%1.1f", pct*100),"%")), position=position_stack(vjust=0.5)) +
#scale_fill_manual(guide_legend(title="Sexo"), values = c("#D95F02", "#1B9E77"),labels = c("Feminino","Masculino")) + 
  labs(x = 'Seguro', y = 'Frequência Absoluta', title = "Distribuição de Resposta")

hist_resp
```


```{r}

hist_reg <- ggplot(data %>% count(Regiao, Resposta) %>%    
         mutate(pct=n/sum(n)),
       aes(as.factor(Regiao), n)) +
  geom_bar(stat="identity") +
  #geom_text(aes(label=paste0(sprintf("%1.1f", pct*100),"%")), position=position_stack(vjust=0.5)) +
#scale_fill_manual(guide_legend(title="Sexo"), values = c("#D95F02", "#1B9E77"),labels = c("Feminino","Masculino")) + 
  labs(x = 'Regiões', y = 'Frequência Absoluta', title = "Distribuição de Regiões")

hist_reg


```



```{r}
ggplot(data, aes(x=as.factor(Resposta), y=Cmaquina1)) + 
  geom_boxplot(notch=FALSE, fill = "#1B9E77", color = 'black') +
  #scale_x_discrete(labels = c('Sem seguro', 'Seguro Completo'))+
  labs(title = 'Idade por Seguro',
       x = 'Seguro',
       y = 'Idade')


ggplot(data, aes(x=as.factor(Resposta), y=Cmaquina2)) + 
  geom_boxplot(notch=FALSE, fill = "#1B9E77", color = 'black') +
  #scale_x_discrete(labels = c('Sem seguro', 'Seguro Completo'))+
  labs(title = 'Idade por Seguro',
       x = 'Seguro',
       y = 'Idade')



ggplot(data, aes(x=as.factor(Resposta), y=Cmaquina3)) + 
  geom_boxplot(notch=FALSE, fill = "#1B9E77", color = 'black') +
  #scale_x_discrete(labels = c('Sem seguro', 'Seguro Completo'))+
  labs(title = 'Idade por Seguro',
       x = 'Seguro',
       y = 'Idade')


```

